### ISSUE TITLE
Issue with cartopy feature and plt.savefig()

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#13]
Hi all,

`import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib.offsetbox import AnchoredText

def main():
    ax = plt.axes(projection=ccrs.PlateCarree())
    ax.set_extent([80, 170, -45, 30])

    # Put a background image on for nice sea rendering.
    ax.stock_img()

    # Create a feature for States/Admin 1 regions at 1:50m from Natural Earth
    states_provinces = cfeature.NaturalEarthFeature(
        category='cultural',
        name='admin_1_states_provinces_lines',
        scale='50m',
        facecolor='none')

    SOURCE = 'Natural Earth'
    LICENSE = 'public domain'

    ax.add_feature(cfeature.LAND)
    ax.add_feature(cfeature.COASTLINE)
    ax.add_feature(states_provinces, edgecolor='gray')

    # Add a text annotation for the license information to the
    # the bottom right corner.
    text = AnchoredText(r'$\mathcircled{{c}}$ {}; license: {}'
                        ''.format(SOURCE, LICENSE),
                        loc=4, prop={'size': 12}, frameon=True)
    ax.add_artist(text)

    plt.show()
    plt.savefig('toto.png')

if __name__ == '__main__':
    main()`

does not wok unless we comment the `plt.savefig('toto.png')` line.
Note this is the basic example in Cartopy documentation: https://scitools.org.uk/cartopy/docs/latest/gallery/feature_creation.html

Error return:
`[sorelm@guppy ~]$ python feature_creation.py
Traceback (most recent call last):
  File "feature_creation.py", line 40, in <module>
    main()
  File "feature_creation.py", line 36, in main
    plt.savefig('toto.png')
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/pyplot.py", line 710, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/figure.py", line 2035, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 513, in print_png
    FigureCanvasAgg.draw(self)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/Cartopy-0.13.1-py3.5-linux-x86_64.egg/cartopy/mpl/geoaxes.py", line 359, in draw
    inframe=inframe)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/metwork-mfext-0.5/opt/python3_scientific/lib/python3.5/site-packages/Cartopy-0.13.1-py3.5-linux-x86_64.egg/cartopy/mpl/feature_artist.py", line 125, in draw
    ax = self.get_axes()
AttributeError: 'FeatureArtist' object has no attribute 'get_axes'`

**Comment by matthieusorel** [comment]
Might be related to ISSUE #12 (to investigate).

**Comment by thefab** [comment]
this online example was added with `0.16` version (we have `0.13` version in metwork)

**Comment by matthieusorel** [comment]
The online example was also available in Cartopy v0.13 version: https://scitools.org.uk/cartopy/docs/v0.13/matplotlib/feature_interface.html
Latest Cartopy version is 0.17.

**Comment by thefab** [comment]
ok sorry for the noise

**Comment by thefab** [comment]
we plan to upgrade most of scientific components for 0.8 version, I think it can help with this bug

**Comment by thebaptiste** [comment]
This issue will be closed in 0.8 version, with use of cartopy 0.17 in python 3.7.
We can't make it work for python2.
