### ISSUE TITLE
Error while importing dask.dataframe

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#144]
Hello,

I have an error while importing dask.dataframe.
```
[sorelm@sotrtm34-sidev T]$ python
Python 3.7.3 (default, Sep 24 2020, 13:37:04)
[GCC 8.3.1 20190311 (Red Hat 8.3.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask.dataframe as dd
Traceback (most recent call last):
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/dask/dataframe/__init__.py", line 15, in <module>
    from .io import (
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/dask/dataframe/io/__init__.py", line 16, in <module>
    from .hdf import read_hdf, to_hdf
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/dask/dataframe/io/hdf.py", line 15, in <module>
    from ... import config, multiprocessing
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/dask/multiprocessing.py", line 9, in <module>
    import cloudpickle
ModuleNotFoundError: No module named 'cloudpickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/dask/dataframe/__init__.py", line 57, in <module>
    raise ImportError(str(e) + "\n\n" + msg)
ImportError: No module named 'cloudpickle'

Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  pip install dask[dataframe] --upgrade  # or pip install
```

Bug with MetWork V0.8 and V1.0

Cheers,
Matthieu

**Comment by thebaptiste** [comment]
`import dask` (the only check we do in integration tests) is ok, but `import dask.dataframe` is not. Same thing with Metwork 0.9 (it's not a new issue with Metwork 1.0).
I was not aware of this possibility to have different dependencies depending on the "submodule" used.

**Comment by thefab** [comment]
yes this is not specific to metwork, I have seen the same thing with manual install

=> let's add dask[dataframe] ?

**Comment by thebaptiste** [comment]
Adding `dask[dataframe]` in `requirements-to-freeze.txt` doesn't bring `cloudpickle` dependency in `requirements3.txt`.
I will have to explicitly add `cloudpickle` in `requirements-to-freeze.txt`
