### ISSUE TITLE
Error in Metwork V1.0 with metpy.plots.SkewT

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#145]
Hello,

I have an error while trying to import metpy.plots.SkewT.

```
>>> from metpy.plots import SkewT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/metpy/plots/__init__.py", line 12, in <module>
    from .declarative import *  # noqa: F403
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/metpy/plots/declarative.py", line 14, in <module>
    from . import cartopy_utils, ctables
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/metpy/plots/cartopy_utils.py", line 43, in <module>
    USCOUNTIES = MetPyMapFeature('us_counties', '20m', facecolor='None', edgecolor='black')
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/metpy/plots/cartopy_utils.py", line 17, in __init__
    super(MetPyMapFeature, self).__init__('', name, scale, **kwargs)
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/cartopy/feature/__init__.py", line 264, in __init__
    self._validate_scale()
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/cartopy/feature/__init__.py", line 274, in _validate_scale
    'Valid scales are "110m", "50m", and "10m".'
ValueError: 20m is not a valid Natural Earth scale. Valid scales are "110m", "50m", and "10m".
```

Seeems that we are not alone: https://github.com/Unidata/MetPy/issues/1368

Cheers,
Matthieu

**Comment by thefab** [comment]
as I understand it, it's an upstream bug (and not a metwork one)

we should update cartopy from 0.17 to 0.18?

@matthieusorel do you understand the same thing than me?

**Comment by matthieusorel** [comment]
Yep ! 
We should give it a try !

**Comment by thebaptiste** [comment]
Not that simple : we are already in Cartopy 0.18. May be it's MetPy we should upgrade...
I'm working on it (soon).
