### ISSUE TITLE
Geopandas needs descartes package

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#153]
Hello,

In MetWork V1.0, in order to plot geopandas polygons, package descartes is needed.

```
shp_sz[shp_sz['Study Zone'].isin(list_ok)].plot()
Traceback (most recent call last):
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/geopandas/plotting.py", line 120, in _plot_polygon_collection
    from descartes.patch import PolygonPatch
ModuleNotFoundError: No module named 'descartes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/geopandas/geodataframe.py", line 921, in plot
    return plot_dataframe(self, *args, **kwargs)
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/geopandas/plotting.py", line 623, in plot_dataframe
    **style_kwds
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/geopandas/plotting.py", line 414, in plot_series
    ax, polys, values_, facecolor=facecolor, cmap=cmap, **style_kwds
  File "/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages/geopandas/plotting.py", line 123, in _plot_polygon_collection
    "The descartes package is required for plotting polygons in geopandas. "
ImportError: The descartes package is required for plotting polygons in geopandas. You can install it using 'conda install -c conda-forge descartes' or 'pip install descartes'.

```

Cheers,
Matthieu

**Comment by thebaptiste** [comment]
This new feature (polygons plotting with geopandas) will be available with Metwork 1.1
We don't consider it as a fix since descartes is an optional dependency of geopandas and geopandas provides many other features than polygons plotting without descartes, so we won't backport it in Metwork 1.0.

mapclassify, an other python module involved in polygons plotting with geopandas, has also been added with its own dependencies.

**Comment by thebaptiste** [comment]
Could you provide a complete example of plotting polygons with geopandas, so that I can check that no other package is missing ?

**Comment by matthieusorel** [comment]
Sure, the example from geopandas documentation should be enough:
```
import geopandas
world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
world.plot()
```

**Comment by thebaptiste** [comment]
Thanks @matthieusorel . I checked the fix is ok.
