### ISSUE TITLE
V0.8: urllib.error.URLError

### ISSUE THREAD

**Issue by matthieusorel** [metwork-framework/mfextaddon_scientific#58]
Hi,

I have an issue with V0.8 while executing the following script:
```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib.offsetbox import AnchoredText


def main():
    ax = plt.axes(projection=ccrs.PlateCarree())
    ax.set_extent([80, 170, -45, 30])

    # Put a background image on for nice sea rendering.
    ax.stock_img()

    # Create a feature for States/Admin 1 regions at 1:50m from Natural Earth
    states_provinces = cfeature.NaturalEarthFeature(
        category='cultural',
        name='admin_1_states_provinces_lines',
        scale='50m',
        facecolor='none')

    SOURCE = 'Natural Earth'
    LICENSE = 'public domain'

    ax.add_feature(cfeature.LAND)
    ax.add_feature(cfeature.COASTLINE)
    ax.add_feature(states_provinces, edgecolor='gray')

    # Add a text annotation for the license information to the
    # the bottom right corner.
    text = AnchoredText(r'$\mathcircled{{c}}$ {}; license: {}'
                        ''.format(SOURCE, LICENSE),
                        loc=4, prop={'size': 12}, frameon=True)
    ax.add_artist(text)

    plt.show()
    plt.savefig('toto.png')


if __name__ == '__main__':
    main()
```

I get the following error message:
```
Traceback (most recent call last):                                                                                                                            
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 1317, in do_open                                                       
    encode_chunked=req.has_header('Transfer-encoding'))                                                                                                       
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 388, in draw
    inframe=inframe)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/cartopy/mpl/feature_artist.py", line 164, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/cartopy/feature/__init__.py", line 303, in intersecting_geometries
    return super(NaturalEarthFeature, self).intersecting_geometries(extent)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/cartopy/feature/__init__.py", line 120, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/cartopy/feature/__init__.py", line 287, in geometries
    name=self.name)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/cartopy/io/shapereader.py", line 359, in natural_earth
    return ne_downloader.path(format_dict)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/cartopy/io/__init__.py", line 222, in path
    result_path = self.acquire_resource(target_path, format_dict)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/cartopy/io/shapereader.py", line 414, in acquire_resource
    shapefile_online = self._urlopen(url)
  File "/opt/metwork-mfext-0.8/opt/python3_scientific/lib/python3.7/site-packages/cartopy/io/__init__.py", line 261, in _urlopen
    return urlopen(url)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>
```

**Comment by thebaptiste** [comment]
I think it is not a Metwork issue but a "new https proxy" issue...
The right certificate is probably not installed on the machine you are working on.

**Comment by matthieusorel** [comment]
Works fine after adding those lines:

i```
mport requests
requests.packages.urllib3.disable_warnings()

import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context
```

**Comment by thefab** [comment]
great for the fix!

=> we close this issue

**Comment by thebaptiste** [comment]
By the way, this script (without your ssl fix) is one of the scripts executed when we run integration tests on mfext.

**Comment by willemet** [comment]
hi,

In the shapely page install https://pypi.org/project/Shapely/
we can read : 
If you want to build Shapely from source for compatibility with other modules that depend on GEOS (such as cartopy or osgeo.ogr) or want to use a different version of GEOS than the one included in the project wheels you should first install the GEOS library, Cython, and Numpy on your system (using apt, yum, brew, or other means) and then direct pip to ignore the binary wheels.

$ pip install shapely --no-binary shapely

Perhaps, it will be a better fix for this issue (I have not tested). 

thanks for metwork, it's great
Jean-Marie
